package com.ususstudios.noway.datagen;

import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import org.json.JSONArray;
import org.json.JSONObject;
import com.ususstudios.noway.components.*;

/**
 * MapGeneration is an API for generating map JSONs.
 */
public class MapGeneration {
    public static void generate() {
        generateMap("main", "Main (Test Map)", 50, 50, 23, 21,
                new String[]{"Neverending Maze"},
                new ArrayList<>(){{
                    add(new HashMap<Class<? extends Component>, Object[]>(){{
                        put(PositionComponent.class, new Object[]{ 21, 21 });
                        put(SpritesheetComponent.class, new Object[]{ "entity/npc/gatekeeper_sheet", 0, 0, 3, 4, 1, 1 });
                        put(CollisionComponent.class, new Object[]{ 0.6, 1.0001f, 0.2, 0.0001f });
                    }});
                }},
                new ArrayList<>(){{
                    add(new String[]{
      "AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AE AD AD AD AD AD AD AE AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AE AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AE AD AD AE AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AE AD AD AD AD AD AD AE AD AD AD AD AD AD AE AD AD AD AD AD AD",
      "AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AB AB AB AB AB AB AB AD AD AD AD AD AB AB AB AC AB AB AB AB AD AD AD AD AD AB AB Aa AY AY AY AY AY AY Ab AD AD AD AE AD AD AD AD",
      "AD AD AE AD AD AD AD AB AA AA AA AA AA AB AB AB AB AB AB AB AB AD AD AD AD AD AB AB AB AB AB AB AB AB AW AR AR AR AR AR AR AV AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AB AA Ae Ae Ae AA AB AB AB AB AB AB AB AB AD AD AD AD AD AB AB AB AB AB AB AB AB AW AR Ah AR AR AR AR AV AD AD AD AD AD AD AD AD",
      "AD AD AD AE AD AD AD AB AA Ae Ae Ae AA AB AB AB AB AB AB AB AB AD AD AD AD AD AC AB AB AB AB AB AB AB AW AR AR AR AR AR AR AV AD AD AE AD AD AD AD AD",
      "AD AD AD AD AE AD AD AB AA Ae Ae Ae AA AB AB AB AB AB AB AB AB AD AD AD AD AD AB AB AB AB AB AB AB AB AW AR AR AR AR AR AR AV AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AB AA AA Ae AA AA AB AB AB AB AB AB AB AC AB AB Aj AB AB AB AB AB AB AB AB AB AB Ac AT AT AU AR AS AT Ad AD AE AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB Aa AY Ab AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AE AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AD AD AD AD AD AE AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AD AD AD AD AD AD AE AD AD AD",
      "AD AD AE AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB Aa AY AZ AR AV AD AD AD AE AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AW AR AR AR AV AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AE AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AW Ah AV AB AB AB AB AB AB AB AB AB AB AW AR AS AT Ad AD AD AE AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB Aa AY AY AY AY AY AY AY AY AZ AR AX AY AY AY AY AY AY AY AY AY AY AZ AR AV AB AB AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AE AD AD AB AB AB AB AC AW AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AR AV AB AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AE AD AB AB AB AB AB Ac AT AT AT AT AT AT AT AT AU AR AS AT AT AT AT AT AT AT AT AT AT AU AR AV AB AD AD AE AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AW AR AV AB AD AD AD AD AD AE AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AW AR AV AC AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AE AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AW AR AV AB AD AD AD AD AE AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB AB Ai AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AW AR AV AB AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AE AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AW AR AV AB AD AD AE AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AW AR AV AB AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AE AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB Ac AT Ad AB AD AD AD AD AD AE AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB Ai AC AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB AB AD AD AD AD AE AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB AB AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AE AD AD AD AB AB AB AB AC AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB AB AD AD AD AD AD AD AD AD AE AD AD AD",
      "AD AD AD AD AD AD AD AD AD AC AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB AC AD AD AD AE AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AW AR AV AB AB AB AB AB AB AB AB AB AB AB AB Ai AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AE AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB Ac AT Ad AB AB AB AB AB AB AB AB AB AB AC AB AB AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AD AD AD AD AD AE AD AD AD AD AD",
      "AD AD AD AD AD AD AE AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AC AB AB AB AB AB AC AB AB AB AB AB AB AB AB AB Ai AB AC AB AB AD AD AE AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB Ak AB AB AB AB AB AB AB AB AB AC AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AD AD AD AD AD AD AD AD AD AD",
      "AD AD AE AD AD AD AD AD AB AB AB AB AB AB AB AB AB AB AB AB AB AB Ai AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AB AD AD AD AD AD AE AD AD AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB AB AB AD AD AD AD AB AB AB AB AB AC AB AB AD AD AD AD AB AB AB AB AB AB AB AC AB AD AD AD AD AD AD AD AE AD AD",
      "AD AD AD AD AD AD AD AD AB AB AB AB AB AB AD AD AD AD AD AD AB AB AB AB AB AB AD AD AD AD AD AB AB AB AB AB AB AB AB AB AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AB AC AB AB AB AB AD AD AD AD AE AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD",
      "AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AE AD AD AD AD AD AD",
      "AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AE AD AD AD AD",
      "AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD AD"
                    });
                    add(new String[] {
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AN AJ AJ AJ AJ AJ AJ AJ AO AA AA AA AN AJ AJ AJ AJ AJ AJ AJ AJ AO AA AA AA AN AJ AJ AJ AJ AJ AJ AJ AJ AJ AJ AO AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Ag Ag Ag Ag Ag Ag AG AJ AJ AJ AI Ag AA AA AA AA AA AA AA AG AJ AJ AJ AI Ag Ag AA AA AA AA AA AA AA Ab AM AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Af Af Af Af Af Ag Ag Ag Ag Ag Ag Ag AA AF AL AL AL AH AA Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Af AA AA AA Af Ag Ag Ag Ag Ag Ag Ag AA AM AA AA AA AK AA Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Af AA AA AA Af Ag Ag Ag Ag Ag Ag Ag AA AM AA AA AA AK AA Ag Ag Ag Ag AA Ag Ag AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Af AA AA AA Af Ag Ag Ag Ag Ag Ag Ag AA AG AJ AJ AJ AI AA Ag Ag Ag Ag AA Ag Ag AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Af Af AA Af Af Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AA AA Ag Ag Ag Ag AA AA AA AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Ag Ag AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA Ab Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AF AL AQ AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AK Ag Ag Ag AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AP AL AH Ag AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AK Ag AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AN AI Ag AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA Ag Ag Ag AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA Ag AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA Ag Ag Ag AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AF AQ AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA AA Ag Ag AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AP AH AA Ag Ag AA Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AK AA Ag Ag AA Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AN AI AA Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA AA Ag Ag Ag Ag AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA Ag Ag Ag Ag Ag AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA Ag Ag Ag Ag Ag AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA AA AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AM AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK AA AA AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA Ag AF AQ AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AP AH AA AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AM AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AK AA AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AM AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AK AA AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AM AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AK AA AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AM AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AN AI Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AG AO AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AA AA AA Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AG AO AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AA AA AA AA AA Ag Ag Ag Ag Ag AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK Ag Ag Ag Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AA AA AA AA AA Ag Ag Ag Ag AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK Ag Ag AA Ag Ag Ag Ag Ag Ag Ag AA AA AA AA AA AA AA AA AA AA AA Ag Ag Ag AA AA AA AA AA Ag AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK Ag Ag AA Ag AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA Ag AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK Ag Ag AA AA AA Ag Ag AF AL AL AH AA AA AA AA AA AA AA AA AF AL AL AH AA AA AA AA AA AA AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AK Ag Ag Ag Ag Ag Ag AF AQ AA AA AP AH AA AA AA AA AA AA AF AQ AA AA AK AA AA Ag AA AA Ag AA AA AA AM AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AP AL AL AL AL AL AL AQ AA AA AA AA AP AL AL AL AL AL AL AQ AA AA AA AP AH AA AA AA AA AA AA AF AL AQ AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AP AL AL AL AL AL AL AQ AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA"
                    });
                    add(new String[]{
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AP AL AL AL AL AL AL AQ AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA",
      "AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA"
                    });
                }});
    }

    public static void generateMap(String filename, String name, int sizeX, int sizeY, int spawnX, int spawnY,
            String[] songs, List<HashMap<Class<? extends Component>, Object[]>> entities, List<String[]> mapLayers) {
        JSONObject object = new JSONObject();

        object.put("name", name);
        object.put("size", new int[]{sizeX, sizeY});
        object.put("spawn", new int[]{spawnX, spawnY});
        object.put("songs", songs);
        JSONArray entitiesArray = new JSONArray();
        for (HashMap<Class<? extends Component>, Object[]> e : entities) {
            JSONArray entity = new JSONArray();
            for (HashMap.Entry<Class<? extends Component>, Object[]> entry : e.entrySet()) {
                JSONArray comp = new JSONArray();
                comp.put(entry.getKey().getName());
                for (Object arg : entry.getValue()) {
                    comp.put(arg);
                }
                entity.put(comp);
            }
            entitiesArray.put(entity);
        }
        object.put("entities", entitiesArray);

        object.put("map", mapLayers);

        try (FileWriter file = new FileWriter("../assets/values/maps/" + filename + ".json")) {
            file.write(object.toString());
            file.flush();
            System.out.println("Wrote values/maps/" + filename + ".json");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
